# Generated by Django 4.0.1 on 2022-01-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registered_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=25)),
                ('Emailid', models.CharField(max_length=25)),
                ('Password', models.CharField(max_length=10)),
            ],
        ),
    ]
