# Generated by Django 4.0.1 on 2022-01-04 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registered_users',
            old_name='Emailid',
            new_name='emailid',
        ),
        migrations.RenameField(
            model_name='registered_users',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='registered_users',
            old_name='Username',
            new_name='username',
        ),
    ]
